# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06d118204ece9125d19ace950e69ac2f"
name = "saleperson-app"
handle = "saleperson-app"
application_url = "https://modules-injured-bi-conferences.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "kobe-pottery.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://modules-injured-bi-conferences.trycloudflare.com/auth/callback",
  "https://modules-injured-bi-conferences.trycloudflare.com/auth/shopify/callback",
  "https://modules-injured-bi-conferences.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
